{% set name = "prophecy-build-tool" %}
{% set version = "1.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/prophecy-build-tool-{{ version }}.tar.gz
  sha256: b8bf31b47a930f8c76d470a8af5837f08654e3f97867b22e5b4b099e2f290dd8

build:
  entry_points:
    - pbt = pbt:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests >=2.28.0
    - pyyaml >=6.0
    - databricks-cli >=0.17.7
    - rich >=12.5.1
    - wheel
    - python-build
    - pyspark >=3.3.0,<3.4.0
    - google-cloud-secret-manager ==2.16.2
    - google-cloud-storage ==2.10.0
    - pydantic >=1.10,<2.0
    - pydantic-yaml ==1.1.1
    - boto3 >=1.26.157,<1.27.0 #<1.29.0
    - tenacity ==8.2.3

test:
  imports:
    - pbt
  commands:
    - pip check
    - pbt --help
  requires:
    - pip

about:
  home: https://github.com/SimpleDataLabsInc/prophecy-build-tool
  summary: Prophecy-build-tool (PBT) provides utilities to build and distribute projects created from the Prophecy IDE.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
